---
apiVersion: v1
kind: ConfigMap
metadata:
  name: python-versions
  namespace: {{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "echoserver")) | nindent 2 }}
data:
  pythonVersions: {{ .Values.echoserver.internal.pythonVersions | toJson | quote }}
