---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echoserver
  namespace: {{ .Chart.Name }}
  {{- include "helm_lib_module_labels" (list . (dict "app" "echoserver")) | nindent 2 }}
spec:
  replicas: {{ .Values.echoserver.replicas }}
  selector:
    matchLabels:
      app: echoserver
  template:
    metadata:
      labels:
        app: echoserver
    spec:
      containers:
        - image: {{ include "helm_lib_module_image" (list . "echoserver") }}
          imagePullPolicy: IfNotPresent
          name: echoserver
          ports:
            - containerPort: 80
          env:
            - name: PORT
              value: "80"
