{{- if .Values.echoserver.registry }}
---
apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: registrysecret
  namespace: {{ .Chart.Name }}
data:
  .dockerconfigjson: {{ .Values.echoserver.registry.dockercfg }}
{{- end }}
